name: jamia_app
description: ????? ????? ????? ????? ????????? ?? ???

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/jamia.html
